### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by micycle8778** [RainbowAsteroids/Portal2D#1]
- [x] Remove debug terminal for Windows 5c94c0a
- [x] Add logo 5c94c0a
- [x] Remove inverse portal bug a15e0ba 360ffae
- [x] Add some enemies 952387c
- [ ] Do something with `README.md`
- [ ] Change turret model
- [x] Make death screen 360ffae 9bc090d
- [x] Make in-game UI f15af4e 3a9488d
- [x] Make title screen 360ffae
- [x] Pause menu 51b7221
- [x] Level select 51b7221
- [x] Update res to 1920x1080 55332df
- [ ] Add a "You Win!" screen
- [ ] Add some display artwork in the title screen
- [ ] Make credits screen
- [ ] Add some more levels (9/100?)
